[package]
name = "loom_macro"
version = "0.0.1"
edition = "2018"
autotests = false
publish = false

[lib]
proc-macro = true

[dependencies]
loom = "0.2.14"
syn = { version = "0.15", features = ["extra-traits", "full", "visit-mut"] }
proc-macro2 = "0.4"
quote = "0.6"